[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jcm"
version = "1.0"
dependencies = [
    "numpy",
    "scipy",
    "tqdm",
    "sklearn",
    "matplotlib",
]